spring:
  application:
    name: artbite
  profiles:
    active: dev # 기본적으로 dev 환경 사용 (개발 시)
    include: secret, oauth2 # secret, oauth2 설정 포함
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari: # HikariCP specific properties
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 30000
      auto-commit: true
  h2:
    console:
      enabled: true
  jpa:
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update # 개발 환경 기본값, 프로필별로 오버라이드
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}