package com.okebari.artbite.membership.service;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import java.time.LocalDate;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import com.okebari.artbite.common.exception.BusinessException;
import com.okebari.artbite.common.exception.ErrorCode;
import com.okebari.artbite.domain.membership.Membership;
import com.okebari.artbite.domain.membership.MembershipPlanType;
import com.okebari.artbite.domain.membership.MembershipRepository;
import com.okebari.artbite.domain.membership.MembershipStatus;
import com.okebari.artbite.domain.user.User;
import com.okebari.artbite.domain.user.UserRepository;
import com.okebari.artbite.domain.user.UserRole;
import com.okebari.artbite.membership.dto.MembershipStatusResponseDto;

@ExtendWith(MockitoExtension.class)
class MembershipServiceTest {

	@Mock
	private MembershipRepository membershipRepository;

	@Mock
	private UserRepository userRepository;

	@InjectMocks
	private MembershipService membershipService;

	private User testUser;

	@BeforeEach
	void setUp() {
		testUser = User.builder()
			.email("test@example.com")
			.password("password")
			.role(UserRole.USER)
			.enabled(true)
			.accountNonExpired(true)
			.accountNonLocked(true)
			.credentialsNonExpired(true)
			.tokenVersion(0)
			.build();
		// Set ID for the mocked user, as it's generated by DB in real scenario
		ReflectionTestUtils.setField(testUser, "id", 1L);
	}

	@Test
	@DisplayName("멤버십 취소 성공")
	void cancelMembership_success() {
		// Given
		Membership activeMembership = Membership.builder()
			.user(testUser)
			.status(MembershipStatus.ACTIVE)
			.planType(MembershipPlanType.DEFAULT_MEMBER_PLAN)
			.startDate(LocalDate.now().minusMonths(1).atStartOfDay())
			.endDate(LocalDate.now().plusMonths(1).atStartOfDay())
			.autoRenew(true)
			.build();

		when(userRepository.findById(testUser.getId())).thenReturn(Optional.of(testUser));
		when(membershipRepository.findTopByUserAndStatusOrderByStartDateDesc(testUser, MembershipStatus.ACTIVE))
			.thenReturn(Optional.of(activeMembership));
		when(membershipRepository.save(any(Membership.class))).thenAnswer(invocation -> invocation.getArgument(0));

		// When
		membershipService.cancelMembership(testUser.getId());

		// Then
		assertThat(activeMembership.getStatus()).isEqualTo(MembershipStatus.CANCELED);
		assertThat(activeMembership.isAutoRenew()).isFalse();
		verify(membershipRepository, times(1)).save(activeMembership);
	}

	@Test
	@DisplayName("멤버십 취소 실패 - 활성 멤버십 없음")
	void cancelMembership_fail_noActiveMembership() {
		// Given
		when(userRepository.findById(testUser.getId())).thenReturn(Optional.of(testUser));
		when(membershipRepository.findTopByUserAndStatusOrderByStartDateDesc(testUser, MembershipStatus.ACTIVE))
			.thenReturn(Optional.empty());

		// When & Then
		BusinessException exception = assertThrows(BusinessException.class,
			() -> membershipService.cancelMembership(testUser.getId()));
		assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.MEMBERSHIP_NOT_FOUND);
		verify(membershipRepository, never()).save(any(Membership.class));
	}

	@Test
	@DisplayName("멤버십 정보 조회 성공 - 활성 멤버십 존재")
	void getMembershipInfo_success_activeMembership() {
		// Given
		Membership activeMembership = Membership.builder()
			.user(testUser)
			.status(MembershipStatus.ACTIVE)
			.planType(MembershipPlanType.DEFAULT_MEMBER_PLAN)
			.startDate(LocalDate.now().minusMonths(1).atStartOfDay())
			.endDate(LocalDate.now().plusMonths(1).atStartOfDay())
			.autoRenew(true)
			.build();

		when(userRepository.findById(testUser.getId())).thenReturn(Optional.of(testUser));
		when(membershipRepository.findTopByUserAndStatusInOrderByStartDateDesc(eq(testUser), anyList()))
			.thenReturn(Optional.of(activeMembership));

		// When
		MembershipStatusResponseDto result = membershipService.getMembershipInfo(testUser.getId());

		// Then
		assertThat(result).isNotNull();
		assertThat(result.getStatus()).isEqualTo(MembershipStatus.ACTIVE);
		assertThat(result.getPlanType()).isEqualTo(MembershipPlanType.DEFAULT_MEMBER_PLAN);
	}

	@Test
	@DisplayName("멤버십 정보 조회 성공 - 활성 멤버십 없음")
	void getMembershipInfo_success_noActiveMembership() {
		// Given
		when(userRepository.findById(testUser.getId())).thenReturn(Optional.of(testUser));
		when(membershipRepository.findTopByUserAndStatusInOrderByStartDateDesc(eq(testUser), anyList()))
			.thenReturn(Optional.empty());

		// When & Then
		BusinessException exception = assertThrows(BusinessException.class,
			() -> membershipService.getMembershipInfo(testUser.getId()));
		assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.MEMBERSHIP_NOT_FOUND);
	}

	@Test
	@DisplayName("멤버십 정보 조회 실패 - 사용자 없음")
	void getMembershipInfo_fail_userNotFound() {
		// Given
		when(userRepository.findById(testUser.getId())).thenReturn(Optional.empty());

		// When & Then
		BusinessException exception = assertThrows(BusinessException.class,
			() -> membershipService.getMembershipInfo(testUser.getId()));
		assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.AUTH_USER_NOT_FOUND);
	}
}
